{% set name = "pyflow" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wonderworks-software/PyFlow/archive/{{ version }}.tar.gz
  sha256: 73fc2fc6d84377853a95502a45908065c7717111276bc63741f22906810fbb2f

build:
  number: 0
  script: '{{ PYTHON }} -m pip install .  -vv '
  noarch: python
  entry_points:
    - pyflow = PyFlow.Scripts:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyrr
    - qt.py
    - blinker
    - nine
    - pyside2
    - docutils

test:
  imports:
    - PyFlow

about:
  home: https://wonderworks-software.github.io/PyFlow/
  license: Apache-2.0
  license_file: LICENSE
  summary: PyFlow is a general purpose visual scripting framework for python.
  doc_url: https://github.com/wonderworks-software/PyFlow
  dev_url: https://github.com/wonderworks-software/PyFlow

extra:
  recipe-maintainers:
    - looooo
